model: "gemini-2.5-flash"
retrieve_model: "gemini-2.5-flash"
gemini_api_key: "AIzaSyDRe4jfUtykPhHf_A6uT9z-5ErZBlN0VxE"
if_thinning: false
min_token_threshold: 5000
summary_token_threshold: 200
if_add_node_id: "yes"
if_add_node_summary: "yes"
if_add_doc_description: "yes"
if_add_node_text: "yes"
